;================================================================================
;
; Messages and User Interface data tables
;
;================================================================================
MES0		DB	"                ",0
MES1		DB	"  MicroProStar  ",0
MES2		DB	"  Version 2.0x  ",0
MES3		DB	"ADC CH    = XXXX",0
MES4		DB	"   Aircraft #   ",0
MES5		DB	"     53.X MHz   ",0
MES6		DB	"       OFF      ",0
MES7		DB	" Accept? Yes No ",0
MES8		DB	" Press   Option ",0
MES9		DB	"       ",0
MES10		DB	"    Student     ",0
MES11		DB	" Yes No ",0
MES12		DB	"Stdnt",0
MES14		DB	" 50.XX MHz  CHX ",0
MES15		DB	"xBld RPM = xxxxx",0
MES16		DB	"Retracts are UP!",0
MES17		DB	"  Format Flash  ",0
MES19		DB	"  Formatting... ",0
MES20		DB	"   Copying...   ",0
MES22		DB	" 72.XX MHz CHXX ",0
MES23           DB	"REC Volts= XX.XX",0
MES24           DB	"Throttle  Adjust",0
MES25           DB	"Mixer  Move From",0
MES26           DB	" Mixer  Move To ",0
MES27		DB	"   Move Mixer   ",0
MES28		DB	"Clear  From Chan",0

; The following messages are used for the Button ID function. This is the function
; that will display the name of the buttopn pressed on the second line of the display
; for 2 seconds.
IDAILHI		DB	"  AIL D/R HIGH  ",0
IDAILLOW	DB	"  AIL D/R  LOW  ",0
IDELEHI		DB	"  ELE D/R HIGH  ",0
IDELELOW	DB	"  ELE D/R  LOW  ",0
IDRUDHI		DB	"  RUD D/R HIGH  ",0
IDRUDLOW	DB	"  RUD D/R  LOW  ",0
IDSNAPR		DB	"   SNAP RIGHT   ",0
IDSNAPL		DB	"   SNAP  LEFT   ",0
IDAUTOT		DB	"   AUTO  TRIM   ",0
IDPRESET	DB	"     PRESET     ",0

; This is the main calibration message displayed on the top line of the display
; after the calibration mode is entered. 
CALMES0		DB	"   CALIBRATE    ",0

; Calibration options table. This table is used to allow the user to
; select the option he wishes to edit. The parameter at the end of each entry
; is an offset used in the jump table.
CALMES1		DB	"Select  Aircraft",0,LOW CALMES2, HIGH CALMES2 ,LOW CALMES14,HIGH CALMES14,0,0
CALMES2		DB	" Aircraft  name ",0,LOW CALMES3, HIGH CALMES3 ,LOW CALMES1, HIGH CALMES1 ,4,0
CALMES3		DB	"      Timer     ",0,LOW CALMES4 ,HIGH CALMES4 ,LOW CALMES2, HIGH CALMES2 ,8,0
CALMES4 	DB	"      Snap      ",0,LOW CALMES5 ,HIGH CALMES5 ,LOW CALMES3, HIGH CALMES3 ,D'12',0
CALMES5 	DB	"     Servos     ",0,LOW CALMES6 ,HIGH CALMES6 ,LOW CALMES4 ,HIGH CALMES4 ,D'16',0
CALMES6 	DB	"     Mixers     ",0,LOW CALMES7 ,HIGH CALMES7 ,LOW CALMES5 ,HIGH CALMES5 ,D'20',0
CALMES7 	DB	"     Switch     ",0,LOW CALMES8 ,HIGH CALMES8 ,LOW CALMES6 ,HIGH CALMES6 ,D'24',0
CALMES8 	DB	"    Options     ",0,LOW CALMES10,HIGH CALMES10,LOW CALMES7 ,HIGH CALMES7 ,D'28',0
CALMES10	DB	"  System Setup  ",0,LOW CALMES12,HIGH CALMES12,LOW CALMES8 ,HIGH CALMES8 ,D'32',0
CALMES11	DB	"Select Frequency",0,LOW CALMES12,HIGH CALMES12,LOW CALMES10,HIGH CALMES10,D'46',0
CALMES12	DB	"    Advanced    ",0,LOW CALMES13,HIGH CALMES13,LOW CALMES10,HIGH CALMES10,D'40',0
CALMES13	DB	"   Helicopter   ",0,LOW CALMES14,HIGH CALMES14,LOW CALMES12,HIGH CALMES12,D'44',0
CALMES14	DB	"      EXIT      ",0,LOW CALMES1, HIGH CALMES1 ,LOW CALMES13,HIGH CALMES13,D'48',0

; The following list of messages are display 2nd line prompts used by a number of
; menu functions.
MENA		DB	"Enable          ",0
MRST		DB	"Reset ?         ",0
MZERO		DB	"Zero  ?         ",0
MCLEAR		DB	"Clear ?         ",0
MAFTN		DB	"Aircraft #      ",0
MCAN		DB	"To AFT #        ",0
MBLADES		DB	"Blades =        ",0
MIXORD		DB	"Fxd Frst        ",0
MVOLTS		DB	"Volts           ",0
MSYNC		DB	"Width           ",0
MNUMCH		DB	"Channels        ",0
MSHFINV		DB	"NegShift?       ",0
MPOS		DB	"Pos =           ",0
MGAIN		DB	"Gain            ",0
MINVERT		DB	"Invert?         ",0
MTSEC		DB	"Time (sec)      ",0
MHZ		DB	"Freq, Hz        ",0
MDEFECT		DB	"Defect          ",0
MKHZ		DB	"Freq, KHz       ",0
MDELAY		DB	"Delay           ",0
MLEVEL		DB	"Level           ",0

;
; The following data structures are used by the user interface. The format is:
; "message",0,Next,Last,Type,Opt,ptr1,ptr2,max,min,postcall,precall
;
; Next and Last are 16 bit pointers to the next entries in the menu list.
; Type is the variable type:
;	0 = Pointer to selection table, vertical selection
;	1 = percent input
;	2 = u sec input
;	3 = yes/no input, uses a flag byte
;	4 = Channel, Ail - CH8
;	5 = Byte input
;	6 = Select switch
;	7 = function call, ptr1 is pointer to function 
;	8 = voltage input (byte, .1 volt units)
;	9 = Menu selection table
;	A = yes/no input, uses a flag bit. bit mask in LSB of ptr2
;	B = short signed int
;	C = signed int
; Opt is a set of bit flags:
;	0 = prt2 defines the DriveCh for the u sec input option
;	1 = Pre call flag, Calls this vector before exit
;	2 = Post call flag, fills PostCall variable
;	3 = Load message pointed to by ptr2 on 2nd display line
;	4 = Auto select, exit after select
;	5 = Variable is pointer
;	6 = Load Min, Max
;	7 = Load message to top line
; ptr1 and ptr2 are 16 bit variables
; min max are loaded into input range regs if the opt flag is set
;

; The following tables support the timer calibration options.

MTIMER1		DB	"      Mode      ",0,LOW MTIMER2, HIGH MTIMER2,LOW MTIMER6, HIGH MTIMER6,0,80,LOW TMODES1, HIGH TMODES1,LOW CNTmode, HIGH CNTmode
MTIMER2		DB	"Minutes         ",0,LOW MTIMER3, HIGH MTIMER3,LOW MTIMER1, HIGH MTIMER1,5,40,LOW DWNMins, HIGH DWNMins,0,0,0,0,D'255',0
MTIMER3		DB	"Seconds         ",0,LOW MTIMER4, HIGH MTIMER4,LOW MTIMER2, HIGH MTIMER2,5,40,LOW DWNSecs, HIGH DWNSecs,0,0,0,0,D'255',0
MTIMER4		DB	" Enable  Switch ",0,LOW MTIMER5, HIGH MTIMER5,LOW MTIMER3, HIGH MTIMER3,6,80,LOW TEnaSW, HIGH TEnaSW
MTIMER5		DB	"Throttle        ",0,LOW MTIMER6, HIGH MTIMER6,LOW MTIMER4, HIGH MTIMER4,1,0, LOW Tthres, HIGH Tthres
MTIMER6		DB	"EXIT            ",0,LOW MTIMER1, HIGH MTIMER1,LOW MTIMER5, HIGH MTIMER5,3,0,LOW EXIT,0
 
TMODES1 	DB	"    UP Timer    ",0,LOW TMODES2, HIGH TMODES2, LOW TMODES3, HIGH TMODES3,0,0
TMODES2 	DB	"   Down Timer   ",0,LOW TMODES3, HIGH TMODES3, LOW TMODES1, HIGH TMODES1,1,0
TMODES3 	DB	"Down  Stop Timer",0,LOW TMODES1, HIGH TMODES1, LOW TMODES2, HIGH TMODES2,2,0

; The following tables support the snap calibration options.

SNAP1		DB	"SR AIL          ",0,LOW SNAP2 , HIGH SNAP2 ,LOW SNAP17, HIGH SNAP17,1,40,LOW SR_A, HIGH SR_A,0,0,0FF,0,07E,0
SNAP2		DB	"SR ELE          ",0,LOW SNAP3 , HIGH SNAP3 ,LOW SNAP1 , HIGH SNAP1 ,1,40,LOW SR_E, HIGH SR_E,0,0,0FF,0,07E,0
SNAP3		DB	"SR RUD          ",0,LOW SNAP4 , HIGH SNAP4 ,LOW SNAP2 , HIGH SNAP2 ,1,40,LOW SR_R, HIGH SR_R,0,0,0FF,0,07E,0
SNAP4		DB	"SR THT          ",0,LOW SNAP5 , HIGH SNAP5 ,LOW SNAP3 , HIGH SNAP3 ,1,40,LOW SR_T, HIGH SR_T,0,0,0FF,0,07E,0
SNAP5		DB	"SR AIL ?        ",0,LOW SNAP6 , HIGH SNAP6 ,LOW SNAP4 , HIGH SNAP4 ,3,0,LOW (SR_A+1),HIGH SR_A
SNAP6		DB	"SR ELE ?        ",0,LOW SNAP7 , HIGH SNAP7 ,LOW SNAP5 , HIGH SNAP5 ,3,0,LOW (SR_E+1),HIGH SR_E
SNAP7		DB	"SR RUD ?        ",0,LOW SNAP8 , HIGH SNAP8 ,LOW SNAP6 , HIGH SNAP6 ,3,0,LOW (SR_R+1),HIGH SR_R
SNAP8		DB	"SR THT ?        ",0,LOW SNAP9 , HIGH SNAP9 ,LOW SNAP7 , HIGH SNAP7 ,3,0,LOW (SR_T+1),HIGH SR_T
SNAP9		DB	"SL AIL          ",0,LOW SNAP10, HIGH SNAP10,LOW SNAP8 , HIGH SNAP8 ,1,40,LOW SL_A, HIGH SL_A,0,0,0FF,0,07E,0
SNAP10		DB	"SL ELE          ",0,LOW SNAP11, HIGH SNAP11,LOW SNAP9 , HIGH SNAP9 ,1,40,LOW SL_E, HIGH SL_E,0,0,0FF,0,07E,0
SNAP11		DB	"SL RUD          ",0,LOW SNAP12, HIGH SNAP12,LOW SNAP10, HIGH SNAP10,1,40,LOW SL_R, HIGH SL_R,0,0,0FF,0,07E,0
SNAP12		DB	"SL THT          ",0,LOW SNAP13, HIGH SNAP13,LOW SNAP11, HIGH SNAP11,1,40,LOW SL_T, HIGH SL_T,0,0,0FF,0,07E,0
SNAP13		DB	"SL AIL ?        ",0,LOW SNAP14, HIGH SNAP14,LOW SNAP12, HIGH SNAP12,3,0,LOW (SL_A+1),HIGH SL_A
SNAP14		DB	"SL ELE ?        ",0,LOW SNAP15, HIGH SNAP15,LOW SNAP13, HIGH SNAP13,3,0,LOW (SL_E+1),HIGH SL_E
SNAP15		DB	"SL RUD ?        ",0,LOW SNAP16, HIGH SNAP16,LOW SNAP14, HIGH SNAP14,3,0,LOW (SL_R+1),HIGH SL_R
SNAP16		DB	"SL THT ?        ",0,LOW SNAP17, HIGH SNAP17,LOW SNAP15, HIGH SNAP15,3,0,LOW (SL_T+1),HIGH SL_T
SNAP17		DB	"EXIT            ",0,LOW SNAP1 , HIGH SNAP1 ,LOW SNAP16, HIGH SNAP16,3,0,LOW EXIT, HIGH EXIT

; The following tables support the servo calibration options.

SCHNMES1	DB	"    Aileron     ",0,LOW SCHNMES2,HIGH SCHNMES2,LOW SCHNMES10,HIGH SCHNMES10,9,086,LOW SCALMES1,HIGH SCALMES1,0,0,LOW AilPost,HIGH AilPost,LOW AilPre,HIGH AilPre
SCHNMES2	DB	"    Elevator    ",0,LOW SCHNMES3,HIGH SCHNMES3,LOW SCHNMES1,HIGH SCHNMES1,9,086,LOW SCALMES1,HIGH SCALMES1,0,0,LOW ElePost,HIGH ElePost,LOW ElePre,HIGH ElePre
SCHNMES3	DB	"     Rudder     ",0,LOW SCHNMES4,HIGH SCHNMES4,LOW SCHNMES2,HIGH SCHNMES2,9,086,LOW SCALMES1,HIGH SCALMES1,0,0,LOW RudPost,HIGH RudPost,LOW RudPre,HIGH RudPre
SCHNMES4	DB	"    Throttle    ",0,LOW SCHNMES5,HIGH SCHNMES5,LOW SCHNMES3,HIGH SCHNMES3,9,086,LOW SCALT1,HIGH SCALT1,0,0,LOW ThtPost,HIGH ThtPost,LOW ThtPre,HIGH ThtPre
SCHNMES5	DB	"      CH5       ",0,LOW SCHNMES6,HIGH SCHNMES6,LOW SCHNMES4,HIGH SCHNMES4,9,086,LOW SCH51,HIGH SCH51,0,0,LOW CH5Post,HIGH CH5Post,LOW CH5Pre,HIGH CH5Pre
SCHNMES6	DB	"      CH6       ",0,LOW SCHNMES7,HIGH SCHNMES7,LOW SCHNMES5,HIGH SCHNMES5,9,086,LOW SCH671,HIGH SCH671,0,0,LOW CH6Post,HIGH CH6Post,LOW CH6Pre,HIGH CH6Pre
SCHNMES7	DB	"      CH7       ",0,LOW SCHNMES8,HIGH SCHNMES8,LOW SCHNMES6,HIGH SCHNMES6,9,086,LOW SCH671,HIGH SCH671,0,0,LOW CH7Post,HIGH CH7Post,LOW CH7Pre,HIGH CH7Pre
SCHNMES8	DB	"      CH8       ",0,LOW SCHNMES9,HIGH SCHNMES9,LOW SCHNMES7,HIGH SCHNMES7,9,086,LOW SCH81,HIGH SCH81,0,0,LOW CH8Post,HIGH CH8Post,LOW CH8Pre,HIGH CH8Pre
SCHNMES9	DB	"    Sub Trims   ",0,LOW SCHNMES10,HIGH SCHNMES10,LOW SCHNMES8,HIGH SCHNMES8,9,080,LOW STMENU1, HIGH STMENU1
SCHNMES10	DB	"EXIT            ",0,LOW SCHNMES1,HIGH SCHNMES1,LOW SCHNMES9,HIGH SCHNMES9,3,0,LOW EXIT, HIGH EXIT

; This table is used for ail, ele, and rud calibration
SCALMES1	DB      "Reverse         ",0,LOW SCALMES2,  HIGH SCALMES2, LOW SCALMES10,HIGH SCALMES10,3,4,LOW ServoREV,0,0,0,LOW SrevCPost,HIGH SrevCPost
SCALMES2	DB      "RT/DWN          ",0,LOW SCALMES3,  HIGH SCALMES3, LOW SCALMES1, HIGH SCALMES1 ,2,2,LOW RTDWN,0,0,0,LOW SerLim, HIGH SerLim
SCALMES3	DB      "Center          ",0,LOW SCALMES4,  HIGH SCALMES4, LOW SCALMES2, HIGH SCALMES2 ,2,2,LOW CENTER,0,0,0,LOW SerLim, HIGH SerLim
SCALMES4	DB      "LT/UP           ",0,LOW SCALMES5,  HIGH SCALMES5, LOW SCALMES3, HIGH SCALMES3 ,2,2,LOW LTUP,0,0,0,LOW SerLim, HIGH SerLim
SCALMES5	DB      "Dual Rate       ",0,LOW SCALMES6,  HIGH SCALMES6, LOW SCALMES4, HIGH SCALMES4 ,1,0,LOW DRP,0
SCALMES6	DB      "Trim            ",0,LOW SCALMES7,  HIGH SCALMES7, LOW SCALMES5, HIGH SCALMES5 ,1,0,LOW TRIMP,0
SCALMES7	DB      "AT RST          ",0,LOW SCALMES8,  HIGH SCALMES8, LOW SCALMES6, HIGH SCALMES6 ,3,0,LOW ATRST,0
SCALMES8	DB      "Expo HI         ",0,LOW SCALMES9,  HIGH SCALMES9, LOW SCALMES7, HIGH SCALMES7 ,1,0,LOW EXPOHI,0
SCALMES9	DB      "Expo LOW        ",0,LOW SCALMES10, HIGH SCALMES10,LOW SCALMES8, HIGH SCALMES8 ,1,0,LOW EXPOLOW,0
SCALMES10	DB      "EXIT            ",0,LOW SCALMES1,  HIGH SCALMES1, LOW SCALMES9, HIGH SCALMES9 ,3,0,LOW EXIT,0
          
; Throttle calibration table
SCALT1		DB	"Reverse         ",0,LOW SCALT2,  HIGH SCALT2, LOW SCALT7, HIGH SCALT7,3,4,LOW ServoREV,0,0,0,LOW TrevPost,HIGH TrevPost
SCALT2		DB	"High            ",0,LOW SCALT3,  HIGH SCALT3, LOW SCALT1, HIGH SCALT1,2,3,LOW TMH,3,chTHT,0,LOW SerLim, HIGH SerLim
SCALT3		DB	"Low             ",0,LOW SCALT4,  HIGH SCALT4, LOW SCALT2, HIGH SCALT2,2,3,LOW TBH,3,chTHT,0,LOW SerLim, HIGH SerLim
SCALT4		DB	"Trim            ",0,LOW SCALT5,  HIGH SCALT5, LOW SCALT3, HIGH SCALT3,1,0,LOW TPT,3
SCALT5		DB	"Trim Mode       ",0,LOW SCALT6,  HIGH SCALT6, LOW SCALT4, HIGH SCALT4,0,0,LOW SCALTMODE1, HIGH SCALTMODE1,LOW TMODE, 3
SCALT6		DB	"Preset          ",0,LOW SCALT7,  HIGH SCALT7, LOW SCALT5, HIGH SCALT5,2,3,LOW Tpreset,3,chTHT,0,LOW SerLim, HIGH SerLim
SCALT7		DB      "EXIT            ",0,LOW SCALT1,  HIGH SCALT1, LOW SCALT6, HIGH SCALT6,3,0,LOW EXIT,0

; Throttle mode options 
SCALTMODE1	DB	"Trim Mode NORMAL",0,LOW SCALTMODE2,  HIGH SCALTMODE2, LOW SCALTMODE3, HIGH SCALTMODE3,0,0
SCALTMODE2	DB	"Trim Mode    LOW",0,LOW SCALTMODE3,  HIGH SCALTMODE3, LOW SCALTMODE1, HIGH SCALTMODE1,1,0
SCALTMODE3	DB	"Trim Mode   HIGH",0,LOW SCALTMODE1,  HIGH SCALTMODE1, LOW SCALTMODE2, HIGH SCALTMODE2,2,0

; CH5
SCH51		DB	"Reverse         ",0,LOW SCH52,HIGH SCH52,LOW SCH55,HIGH SCH55,3,4,LOW ServoREV,0,0,0,LOW SrevNCPost,HIGH SrevNCPost
SCH52		DB	"High/Up         ",0,LOW SCH53,HIGH SCH53,LOW SCH51,HIGH SCH51,2,2,LOW RTDWN,0,0,0,LOW SerLim, HIGH SerLim
SCH53		DB	"Low/DWN         ",0,LOW SCH54,HIGH SCH54,LOW SCH52,HIGH SCH52,2,2,LOW CENTER,0,0,0,LOW SerLim, HIGH SerLim
SCH54		DB	" CH5  Slew Rate ",0,LOW SCH55,HIGH SCH55,LOW SCH53,HIGH SCH53,8,8E ,LOW CH5stepSize,HIGH CH5stepSize,LOW MTSEC,HIGH MTSEC,LOW PostCH5, HIGH PostCH5, LOW PreCH5, HIGH PreCH5
SCH55		DB      "EXIT            ",0,LOW SCH51,HIGH SCH51,LOW SCH54,HIGH SCH54,3,0,LOW EXIT,0

; CH6, and CH7
SCH671		DB	"Reverse         ",0,LOW SCH672,  HIGH SCH672, LOW SCH674, HIGH SCH674,3,4,LOW ServoREV,0,0,0,LOW SrevNCPost,HIGH SrevNCPost
SCH672		DB	"High/Up         ",0,LOW SCH673,  HIGH SCH673, LOW SCH671, HIGH SCH671,2,2,LOW RTDWN,0,0,0,LOW SerLim, HIGH SerLim
SCH673		DB	"Low/DWN         ",0,LOW SCH674,  HIGH SCH674, LOW SCH672, HIGH SCH672,2,2,LOW CENTER,0,0,0,LOW SerLim, HIGH SerLim
SCH674		DB      "EXIT            ",0,LOW SCH671,  HIGH SCH671, LOW SCH673, HIGH SCH673,3,0,LOW EXIT,0

; CH8
SCH81		DB	"Reverse         ",0,LOW SCH82,HIGH SCH82,LOW SCH86,HIGH SCH86,3,4,LOW ServoREV,0,0,0,LOW SrevCPost,HIGH SrevCPost
SCH82		DB	"A               ",0,LOW SCH83,HIGH SCH83,LOW SCH81,HIGH SCH81,2,3,LOW RTDWN,0,chCH8,0,LOW SerLim, HIGH SerLim
SCH83		DB	"B               ",0,LOW SCH84,HIGH SCH84,LOW SCH82,HIGH SCH82,2,3,LOW CENTER,0,chCH8,0,LOW SerLim, HIGH SerLim
SCH84		DB	"C               ",0,LOW SCH85,HIGH SCH85,LOW SCH83,HIGH SCH83,2,3,LOW LTUP,0,chCH8,0,LOW SerLim, HIGH SerLim
SCH85		DB	" CH8  Slew Rate ",0,LOW SCH86,HIGH SCH86,LOW SCH84,HIGH SCH84,8,8E ,LOW CH8stepSize,HIGH CH8stepSize,LOW MTSEC,HIGH MTSEC,LOW PostCH8, HIGH PostCH8, LOW PreCH8, HIGH PreCH8
SCH86		DB      "EXIT            ",0,LOW SCH81,HIGH SCH81,LOW SCH85,HIGH SCH85,3,0,LOW EXIT,0

; Sub Trim adjustment menu
STMENU1		DB	"ResetAllSubTrims",0,LOW STMENU2 ,HIGH STMENU2 ,LOW STMENU10,HIGH STMENU10,3,08C,LOW YESNO,HIGH YESNO,LOW MRST,HIGH MRST,LOW STreset,HIGH STreset
STMENU2		DB	"Aileron         ",0,LOW STMENU3 ,HIGH STMENU3 ,LOW STMENU1 ,HIGH STMENU1 ,1,2,LOW SubTrim,HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU3		DB	"Elevator        ",0,LOW STMENU4 ,HIGH STMENU4 ,LOW STMENU2 ,HIGH STMENU2 ,1,2,LOW (SubTrim+1),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU4		DB	"Rudder          ",0,LOW STMENU5 ,HIGH STMENU5 ,LOW STMENU3 ,HIGH STMENU3 ,1,2,LOW (SubTrim+2),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU5		DB	"Throttle        ",0,LOW STMENU6 ,HIGH STMENU6 ,LOW STMENU4 ,HIGH STMENU4 ,1,2,LOW (SubTrim+3),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU6		DB	"CH5             ",0,LOW STMENU7 ,HIGH STMENU7 ,LOW STMENU5 ,HIGH STMENU5 ,1,2,LOW (SubTrim+4),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU7		DB	"CH6             ",0,LOW STMENU8 ,HIGH STMENU8 ,LOW STMENU6 ,HIGH STMENU6 ,1,2,LOW (SubTrim+5),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU8		DB	"CH7             ",0,LOW STMENU9 ,HIGH STMENU9 ,LOW STMENU7 ,HIGH STMENU7 ,1,2,LOW (SubTrim+6),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU9		DB	"CH8             ",0,LOW STMENU10,HIGH STMENU10,LOW STMENU8 ,HIGH STMENU8 ,1,2,LOW (SubTrim+7),HIGH SubTrim,0,0,LOW SetSUflag, HIGH SetSUflag
STMENU10	DB	"Exit            ",0,LOW STMENU1 ,HIGH STMENU1 ,LOW STMENU9 ,HIGH STMENU9 ,3,0,LOW EXIT,0


SERVOSEL1	DB	"None",0,LOW SERVOSEL2, HIGH SERVOSEL2,LOW SERVOSEL9, HIGH SERVOSEL9,0,0
SERVOSEL2	DB	" AIL",0,LOW SERVOSEL3, HIGH SERVOSEL3,LOW SERVOSEL1, HIGH SERVOSEL1,1,0
SERVOSEL3	DB	" ELE",0,LOW SERVOSEL4, HIGH SERVOSEL4,LOW SERVOSEL2, HIGH SERVOSEL2,2,0
SERVOSEL4	DB	" RUD",0,LOW SERVOSEL5, HIGH SERVOSEL5,LOW SERVOSEL3, HIGH SERVOSEL3,3,0
SERVOSEL5	DB	" THT",0,LOW SERVOSEL6, HIGH SERVOSEL6,LOW SERVOSEL4, HIGH SERVOSEL4,4,0
SERVOSEL6	DB	" CH5",0,LOW SERVOSEL7, HIGH SERVOSEL7,LOW SERVOSEL5, HIGH SERVOSEL5,5,0
SERVOSEL7	DB	" CH6",0,LOW SERVOSEL8, HIGH SERVOSEL8,LOW SERVOSEL6, HIGH SERVOSEL6,6,0
SERVOSEL8	DB	" CH7",0,LOW SERVOSEL9, HIGH SERVOSEL9,LOW SERVOSEL7, HIGH SERVOSEL7,7,0
SERVOSEL9	DB	" CH8",0,LOW SERVOSEL1, HIGH SERVOSEL1,LOW SERVOSEL8, HIGH SERVOSEL8,8,0

; The following tables support the mixer calibration options.

FMIX1		DB	"    MIXER 1A    ",0,LOW FMIX2,  HIGH FMIX2, LOW FMIX24,HIGH FMIX24,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M1Afrom,HIGH M1Afrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix 
FMIX2		DB	"    MIXER 1B    ",0,LOW FMIX3,  HIGH FMIX3, LOW FMIX1, HIGH FMIX1 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M1Bfrom,HIGH M1Bfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX3		DB	"    MIXER 1C    ",0,LOW FMIX4,  HIGH FMIX4, LOW FMIX2, HIGH FMIX2 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M1Cfrom,HIGH M1Cfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX4		DB	"    MIXER 1D    ",0,LOW FMIX5,  HIGH FMIX5, LOW FMIX3, HIGH FMIX3 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M1Dfrom,HIGH M1Dfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX5		DB	"    MIXER 2A    ",0,LOW FMIX6,  HIGH FMIX6, LOW FMIX4, HIGH FMIX4 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M2Afrom,HIGH M2Afrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX6		DB	"    MIXER 2B    ",0,LOW FMIX7,  HIGH FMIX7, LOW FMIX5, HIGH FMIX5 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M2Bfrom,HIGH M2Bfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX7		DB	"    MIXER 2C    ",0,LOW FMIX8,  HIGH FMIX8, LOW FMIX6, HIGH FMIX6 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M2Cfrom,HIGH M2Cfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX8		DB	"    MIXER 2D    ",0,LOW FMIX9,  HIGH FMIX9, LOW FMIX7, HIGH FMIX7 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M2Dfrom,HIGH M2Dfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX9		DB	"    MIXER 3A    ",0,LOW FMIX10, HIGH FMIX10,LOW FMIX8, HIGH FMIX8 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M3Afrom,HIGH M3Afrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX10		DB	"    MIXER 3B    ",0,LOW FMIX11, HIGH FMIX11,LOW FMIX9, HIGH FMIX9 ,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M3Bfrom,HIGH M3Bfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX11		DB	"    MIXER 3C    ",0,LOW FMIX12, HIGH FMIX12,LOW FMIX10,HIGH FMIX10,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M3Cfrom,HIGH M3Cfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX12		DB	"    MIXER 3D    ",0,LOW FMIX13, HIGH FMIX13,LOW FMIX11,HIGH FMIX11,9,86,LOW FMIXOP1,HIGH FMIXOP1,LOW M3Dfrom,HIGH M3Dfrom,LOW PostMix,HIGH PostMix,LOW PreMix,HIGH PreMix
FMIX13		DB	"   Move Mixer   ",0,LOW FMIX14, HIGH FMIX14,LOW FMIX12,HIGH FMIX12,7, 0,LOW MoveMixer,HIGH MoveMixer
FMIX14		DB	"   AIL to RUD   ",0,LOW FMIX15, HIGH FMIX15,LOW FMIX13,HIGH FMIX13,9,86,LOW FMIXST1,HIGH FMIXST1,LOW M3Dfrom,HIGH M3Dfrom,LOW PostA2R,HIGH PostA2R,LOW PreA2R,HIGH PreA2R
FMIX15		DB	"   RUD to AIL   ",0,LOW FMIX16, HIGH FMIX16,LOW FMIX14,HIGH FMIX14,9,86,LOW FMIXST1,HIGH FMIXST1,LOW M3Dfrom,HIGH M3Dfrom,LOW PostR2A,HIGH PostR2A,LOW PreR2A,HIGH PreR2A
FMIX16		DB	"   RUD to ELE   ",0,LOW FMIX17, HIGH FMIX17,LOW FMIX15,HIGH FMIX15,9,86,LOW FMIXST1,HIGH FMIXST1,LOW M3Dfrom,HIGH M3Dfrom,LOW PostR2E,HIGH PostR2E,LOW PreR2E,HIGH PreR2E
FMIX17		DB	"   THT to ELE   ",0,LOW FMIX18, HIGH FMIX18,LOW FMIX16,HIGH FMIX16,1,88,LOW ThtEle,HIGH ThtEle,LOW MGAIN,HIGH MGAIN
FMIX18		DB	"     VTAIL      ",0,LOW FMIX19, HIGH FMIX19,LOW FMIX17,HIGH FMIX17,3,88,LOW VTAIL, HIGH VTAIL,LOW MENA,HIGH MENA
FMIX19		DB	"     ELEVON     ",0,LOW FMIX20, HIGH FMIX20,LOW FMIX18,HIGH FMIX18,3,88,LOW ELEVON, HIGH ELEVON,LOW MENA,HIGH MENA
FMIX20		DB	"    DUAL AIL    ",0,LOW FMIX21, HIGH FMIX21,LOW FMIX19,HIGH FMIX19,9,80,LOW DUALAILM1, HIGH DUALAILM1
FMIX21		DB	"    DUAL ELE    ",0,LOW FMIX22, HIGH FMIX22,LOW FMIX20,HIGH FMIX20,3,88,LOW DualE, HIGH DualE,LOW MENA,HIGH MENA
FMIX22		DB	"    IDLE  UP    ",0,LOW FMIX23, HIGH FMIX23,LOW FMIX21,HIGH FMIX21,9,80,LOW IDLEUP1, HIGH IDLEUP1
FMIX23		DB	"  Mixer  order  ",0,LOW FMIX24, HIGH FMIX24,LOW FMIX22,HIGH FMIX22,3,88,LOW FixedFirst, HIGH FixedFirst,LOW MIXORD, HIGH MIXORD
FMIX24		DB	"EXIT            ",0,LOW FMIX1,  HIGH FMIX1, LOW FMIX23,HIGH FMIX23,3,0,LOW EXIT,0

MIXSEL1		DB	"    MIXER 1A    ",0,LOW MIXSEL2, HIGH MIXSEL2 ,LOW MIXSEL12,HIGH MIXSEL12,LOW M1Afrom,HIGH M1Afrom
MIXSEL2		DB	"    MIXER 1B    ",0,LOW MIXSEL3, HIGH MIXSEL3 ,LOW MIXSEL1, HIGH MIXSEL1 ,LOW M1Bfrom,HIGH M1Bfrom
MIXSEL3		DB	"    MIXER 1C    ",0,LOW MIXSEL4, HIGH MIXSEL4 ,LOW MIXSEL2, HIGH MIXSEL2 ,LOW M1Cfrom,HIGH M1Cfrom
MIXSEL4		DB	"    MIXER 1D    ",0,LOW MIXSEL5, HIGH MIXSEL5 ,LOW MIXSEL3, HIGH MIXSEL3 ,LOW M1Dfrom,HIGH M1Dfrom
MIXSEL5		DB	"    MIXER 2A    ",0,LOW MIXSEL6, HIGH MIXSEL6 ,LOW MIXSEL4, HIGH MIXSEL4 ,LOW M2Afrom,HIGH M2Afrom
MIXSEL6		DB	"    MIXER 2B    ",0,LOW MIXSEL7, HIGH MIXSEL7 ,LOW MIXSEL5, HIGH MIXSEL5 ,LOW M2Bfrom,HIGH M2Bfrom
MIXSEL7		DB	"    MIXER 2C    ",0,LOW MIXSEL8, HIGH MIXSEL8 ,LOW MIXSEL6, HIGH MIXSEL6 ,LOW M2Cfrom,HIGH M2Cfrom
MIXSEL8		DB	"    MIXER 2D    ",0,LOW MIXSEL9, HIGH MIXSEL9 ,LOW MIXSEL7, HIGH MIXSEL7 ,LOW M2Dfrom,HIGH M2Dfrom
MIXSEL9		DB	"    MIXER 3A    ",0,LOW MIXSEL10,HIGH MIXSEL10,LOW MIXSEL8, HIGH MIXSEL8 ,LOW M3Afrom,HIGH M3Afrom
MIXSEL10	DB	"    MIXER 3B    ",0,LOW MIXSEL11,HIGH MIXSEL11,LOW MIXSEL9, HIGH MIXSEL9 ,LOW M3Bfrom,HIGH M3Bfrom
MIXSEL11	DB	"    MIXER 3C    ",0,LOW MIXSEL12,HIGH MIXSEL12,LOW MIXSEL10,HIGH MIXSEL10,LOW M3Cfrom,HIGH M3Cfrom
MIXSEL12	DB	"    MIXER 3D    ",0,LOW MIXSEL1, HIGH MIXSEL1 ,LOW MIXSEL11,HIGH MIXSEL11,LOW M3Dfrom,HIGH M3Afrom

FMIXST1		DB	"Pos gain        ",0,LOW FMIXST2,HIGH FMIXST2,LOW FMIXST3,HIGH FMIXST3,1,0,LOW Mpg,0
FMIXST2		DB	"Neg gain        ",0,LOW FMIXST3,HIGH FMIXST3,LOW FMIXST1,HIGH FMIXST1,1,0,LOW Mng,0
FMIXST3		DB	"EXIT            ",0,LOW FMIXST1,HIGH FMIXST1,LOW FMIXST2,HIGH FMIXST2,3,0,LOW EXIT,0

FMIXOP1		DB	"From            ",0,LOW FMIXOP2,  HIGH FMIXOP2, LOW FMIXOP10,HIGH FMIXOP10,4,0,LOW Mfrom,0
FMIXOP2		DB	"Table           ",0,LOW FMIXOP3,  HIGH FMIXOP3, LOW FMIXOP1 ,HIGH FMIXOP1 ,0,0,LOW MTBL1,HIGH MTBL1,Low Mtbl,0
FMIXOP3		DB	"To              ",0,LOW FMIXOP4,  HIGH FMIXOP4, LOW FMIXOP2 ,HIGH FMIXOP2 ,4,0,LOW Mto,0
FMIXOP4		DB	"Replace         ",0,LOW FMIXOP5,  HIGH FMIXOP5, LOW FMIXOP3 ,HIGH FMIXOP3 ,3,0,LOW Mreplace,0
FMIXOP5		DB	"ZP              ",0,LOW FMIXOP6,  HIGH FMIXOP6, LOW FMIXOP4 ,HIGH FMIXOP4 ,1,0,LOW Mzp,0
FMIXOP6		DB	"Pos gain        ",0,LOW FMIXOP7,  HIGH FMIXOP7, LOW FMIXOP5 ,HIGH FMIXOP5 ,1,0,LOW Mpg,0
FMIXOP7		DB	"Pos Ind         ",0,LOW FMIXOP8,  HIGH FMIXOP8, LOW FMIXOP6 ,HIGH FMIXOP6 ,4,0,LOW Mpi,0
FMIXOP8		DB	"Neg gain        ",0,LOW FMIXOP9,  HIGH FMIXOP9, LOW FMIXOP7 ,HIGH FMIXOP7 ,1,0,LOW Mng,0
FMIXOP9		DB	"Neg Ind         ",0,LOW FMIXOP10, HIGH FMIXOP10,LOW FMIXOP8 ,HIGH FMIXOP8 ,4,0,LOW Mni,0
FMIXOP10	DB	"EXIT            ",0,LOW FMIXOP1,  HIGH FMIXOP1, LOW FMIXOP9 ,HIGH FMIXOP9 ,3,0,LOW EXIT,0

DUALAILM1	DB	"Enable          ",0,LOW DUALAILM2, HIGH DUALAILM2,LOW DUALAILM6, HIGH DUALAILM6,3,0,LOW DUALA, HIGH DUALA
DUALAILM2	DB	"DIFF            ",0,LOW DUALAILM3, HIGH DUALAILM3,LOW DUALAILM1, HIGH DUALAILM1,1,0,LOW DIFFA, HIGH DIFFA
DUALAILM3	DB	"Flap Pgain      ",0,LOW DUALAILM4, HIGH DUALAILM4,LOW DUALAILM2, HIGH DUALAILM2,1,0,LOW FPgain, HIGH FPgain
DUALAILM4	DB	"Flap Ngain      ",0,LOW DUALAILM5, HIGH DUALAILM5,LOW DUALAILM3, HIGH DUALAILM3,1,0,LOW FPgainN, HIGH FPgainN
DUALAILM5	DB	"CROW            ",0,LOW DUALAILM6, HIGH DUALAILM6,LOW DUALAILM4, HIGH DUALAILM4,3,0,LOW CROWENA, HIGH CROWENA
DUALAILM6	DB	"EXIT            ",0,LOW DUALAILM1, HIGH DUALAILM1,LOW DUALAILM5, HIGH DUALAILM5,3,0,LOW EXIT, 0

IDLEUP1		DB	"Enable          ",0,LOW IDLEUP2, HIGH IDLEUP2,LOW IDLEUP4, HIGH IDLEUP4,3,0,LOW IDLEUP, HIGH IDLEUP
IDLEUP2		DB	"Position A      ",0,LOW IDLEUP3, HIGH IDLEUP3,LOW IDLEUP1, HIGH IDLEUP1,1,0,LOW IDLEUPpA, HIGH IDLEUPpA
IDLEUP3		DB	"Position B      ",0,LOW IDLEUP4, HIGH IDLEUP4,LOW IDLEUP2, HIGH IDLEUP2,1,0,LOW IDLEUPpB, HIGH IDLEUPpB
IDLEUP4		DB	"EXIT            ",0,LOW IDLEUP1, HIGH IDLEUP1,LOW IDLEUP3, HIGH IDLEUP3,3,0,LOW EXIT, 0

MTBL1		DB	"Table       None",0,LOW MTBL2,  HIGH MTBL2, LOW MTBL11,HIGH MTBL11,0,0
MTBL2		DB	"Aircraft Table 1",0,LOW MTBL3,  HIGH MTBL3, LOW MTBL1,HIGH MTBL1,09,0
MTBL3		DB	"Aircraft Table 2",0,LOW MTBL4,  HIGH MTBL4, LOW MTBL2,HIGH MTBL2,0A,0
MTBL4		DB	"Gloabal Table  1",0,LOW MTBL5,  HIGH MTBL5, LOW MTBL3,HIGH MTBL3,1,0
MTBL5		DB	"Gloabal Table  2",0,LOW MTBL6,  HIGH MTBL6, LOW MTBL4,HIGH MTBL4,2,0
MTBL6		DB	"Gloabal Table  3",0,LOW MTBL7,  HIGH MTBL7, LOW MTBL5,HIGH MTBL5,3,0
MTBL7		DB	"Gloabal Table  4",0,LOW MTBL8,  HIGH MTBL8, LOW MTBL6,HIGH MTBL6,4,0
MTBL8		DB	"Gloabal Table  5",0,LOW MTBL9,  HIGH MTBL9, LOW MTBL7,HIGH MTBL7,5,0
MTBL9		DB	"Gloabal Table  6",0,LOW MTBL10, HIGH MTBL10,LOW MTBL8,HIGH MTBL8,6,0
MTBL10		DB	"Gloabal Table  7",0,LOW MTBL11, HIGH MTBL11,LOW MTBL9,HIGH MTBL9,7,0
MTBL11		DB	"Gloabal Table  8",0,LOW MTBL1,  HIGH MTBL1, LOW MTBL10,HIGH MTBL10,8,0

; The following tables support the switch selection calibration options.

SWFUN1		DB	"     AIL DR     ",0,LOW SWFUN2 ,HIGH SWFUN2 ,LOW SWFUN25,HIGH SWFUN25,6,80,LOW SWAILDR, HIGH SWAILDR
SWFUN2		DB	"     ELE DR     ",0,LOW SWFUN3 ,HIGH SWFUN3 ,LOW SWFUN1 ,HIGH SWFUN1 ,6,80,LOW SWELEDR, HIGH SWELEDR
SWFUN3		DB	"     RUD DR     ",0,LOW SWFUN4 ,HIGH SWFUN4 ,LOW SWFUN2 ,HIGH SWFUN2 ,6,80,LOW SWRUDDR, HIGH SWRUDDR
SWFUN4		DB	"     PRESET     ",0,LOW SWFUN5 ,HIGH SWFUN5 ,LOW SWFUN3 ,HIGH SWFUN3 ,6,80,LOW SWPRESET, HIGH SWPRESET
SWFUN5		DB	"    MIXER  1    ",0,LOW SWFUN6 ,HIGH SWFUN6 ,LOW SWFUN4 ,HIGH SWFUN4 ,6,80,LOW SWMIX1, HIGH SWMIX1
SWFUN6		DB	"    MIXER  2    ",0,LOW SWFUN7 ,HIGH SWFUN7 ,LOW SWFUN5 ,HIGH SWFUN5 ,6,80,LOW SWMIX2, HIGH SWMIX2
SWFUN7		DB	"    MIXER  3    ",0,LOW SWFUN8 ,HIGH SWFUN8 ,LOW SWFUN6 ,HIGH SWFUN6 ,6,80,LOW SWMIX3, HIGH SWMIX3
SWFUN8		DB	"      CH5       ",0,LOW SWFUN9 ,HIGH SWFUN9 ,LOW SWFUN7 ,HIGH SWFUN7 ,6,80,LOW SWCH5, HIGH SWCH5
SWFUN9		DB	"    AUTO TRIM   ",0,LOW SWFUN10,HIGH SWFUN10,LOW SWFUN8 ,HIGH SWFUN8 ,6,80,LOW SWATRIM, HIGH SWATRIM
SWFUN10		DB	"     CH8 A      ",0,LOW SWFUN11,HIGH SWFUN11,LOW SWFUN9 ,HIGH SWFUN9 ,6,80,LOW SWCH8A, HIGH SWCH8A
SWFUN11		DB	"     CH8 B      ",0,LOW SWFUN12,HIGH SWFUN12,LOW SWFUN10,HIGH SWFUN10,6,80,LOW SWCH8B, HIGH SWCH8B
SWFUN12		DB	"     CH8 C      ",0,LOW SWFUN13,HIGH SWFUN13,LOW SWFUN11,HIGH SWFUN11,6,80,LOW SWCH8C, HIGH SWCH8C
SWFUN13		DB	"    SNAP  R     ",0,LOW SWFUN14,HIGH SWFUN14,LOW SWFUN12,HIGH SWFUN12,6,80,LOW SWSNAPR, HIGH SWSNAPR
SWFUN14		DB	"    SNAP  L     ",0,LOW SWFUN15,HIGH SWFUN15,LOW SWFUN13,HIGH SWFUN13,6,80,LOW SWSNAPL, HIGH SWSNAPL
SWFUN15		DB	"   Idle Up  1   ",0,LOW SWFUN16,HIGH SWFUN16,LOW SWFUN14,HIGH SWFUN14,6,80,LOW SWIDLEUP1, HIGH SWIDLEUP1
SWFUN16		DB	"   Idle Up  2   ",0,LOW SWFUN17,HIGH SWFUN17,LOW SWFUN15,HIGH SWFUN15,6,80,LOW SWIDLEUP2, HIGH SWIDLEUP2
SWFUN17		DB	"      CROW      ",0,LOW SWFUN18,HIGH SWFUN18,LOW SWFUN16,HIGH SWFUN16,6,80,LOW SWCROW, HIGH SWCROW
SWFUN18		DB	" Trigger Points ",0,LOW SWFUN19,HIGH SWFUN19,LOW SWFUN17,HIGH SWFUN17,9,80,LOW MTP1, HIGH MTP1
SWFUN19		DB	" Throttle  hold ",0,LOW SWFUN20,HIGH SWFUN20,LOW SWFUN18,HIGH SWFUN18 ,6, 80,LOW SWTHOLD, HIGH SWTHOLD
SWFUN20		DB	"  Stunt mode 1  ",0,LOW SWFUN21,HIGH SWFUN21,LOW SWFUN19,HIGH SWFUN19 ,6, 80,LOW SWSTUNT1, HIGH SWSTUNT1
SWFUN21		DB	"  Stunt mode 2  ",0,LOW SWFUN22,HIGH SWFUN22,LOW SWFUN20,HIGH SWFUN20 ,6, 80,LOW SWSTUNT2, HIGH SWSTUNT2
SWFUN22		DB	"IdleUp Norm Mode",0,LOW SWFUN23,HIGH SWFUN23,LOW SWFUN21,HIGH SWFUN21 ,6, 80,LOW SWIDLEUPN, HIGH SWIDLEUPN
SWFUN23		DB	"IdleUp  ST1 Mode",0,LOW SWFUN24,HIGH SWFUN24,LOW SWFUN22,HIGH SWFUN22 ,6, 80,LOW SWIDLEUPST1, HIGH SWIDLEUPST1
SWFUN24		DB	"IdleUp  ST2 Mode",0,LOW SWFUN25,HIGH SWFUN25,LOW SWFUN23,HIGH SWFUN23 ,6, 80,LOW SWIDLEUPST2, HIGH SWIDLEUPST2
SWFUN25		DB	"EXIT            ",0,LOW SWFUN1 ,HIGH SWFUN1 ,LOW SWFUN24,HIGH SWFUN24,3,0,LOW EXIT, HIGH EXIT

MTP1		DB	"Aileron Trig Pos",0,LOW MTP2 ,HIGH MTP2 ,LOW MTP5,HIGH MTP5,1,88,LOW ATP, HIGH ATP,LOW MPOS,HIGH MPOS
MTP2		DB	"Elevator Trg Pos",0,LOW MTP3 ,HIGH MTP3 ,LOW MTP1,HIGH MTP1,1,88,LOW ETP, HIGH ETP,LOW MPOS,HIGH MPOS
MTP3		DB	"Rudder  Trig Pos",0,LOW MTP4 ,HIGH MTP4 ,LOW MTP2,HIGH MTP2,1,88,LOW RTP, HIGH RTP,LOW MPOS,HIGH MPOS
MTP4		DB	"Throttle Trg Pos",0,LOW MTP5 ,HIGH MTP5 ,LOW MTP3,HIGH MTP3,1,88,LOW TTP, HIGH TTP,LOW MPOS,HIGH MPOS
MTP5		DB	"EXIT            ",0,LOW MTP1 ,HIGH MTP1 ,LOW MTP4,HIGH MTP4,3,0,LOW EXIT, HIGH EXIT

; This is the switch programmability table...

SWMENU1		DB	"       ON       ",0,LOW SWMENU2 ,HIGH SWMENU2 ,LOW SWMENU37,HIGH SWMENU37,010,0
SWMENU2		DB	"       OFF      ",0,LOW SWMENU3 ,HIGH SWMENU3 ,LOW SWMENU1 ,HIGH SWMENU1 ,020,0
SWMENU3		DB	"SWA           ON",0,LOW SWMENU4 ,HIGH SWMENU4 ,LOW SWMENU2 ,HIGH SWMENU2 ,080,0
SWMENU4		DB	"SWA          OFF",0,LOW SWMENU5 ,HIGH SWMENU5 ,LOW SWMENU3 ,HIGH SWMENU3 ,000,0
SWMENU5		DB	"SWB           ON",0,LOW SWMENU6 ,HIGH SWMENU6 ,LOW SWMENU4 ,HIGH SWMENU4 ,081,0
SWMENU6		DB	"SWB          OFF",0,LOW SWMENU7 ,HIGH SWMENU7 ,LOW SWMENU5 ,HIGH SWMENU5 ,001,0
SWMENU7		DB	"SWC           ON",0,LOW SWMENU8 ,HIGH SWMENU8 ,LOW SWMENU6 ,HIGH SWMENU6 ,082,0
SWMENU8		DB	"SWC          OFF",0,LOW SWMENU9 ,HIGH SWMENU9 ,LOW SWMENU7 ,HIGH SWMENU7 ,002,0
SWMENU9		DB	"SWD        PRESS",0,LOW SWMENU10,HIGH SWMENU10,LOW SWMENU8 ,HIGH SWMENU8 ,083,0
SWMENU10	DB	"SWD      RELEASE",0,LOW SWMENU11,HIGH SWMENU11,LOW SWMENU9 ,HIGH SWMENU9 ,003,0
SWMENU11	DB	"SWE           ON",0,LOW SWMENU12,HIGH SWMENU12,LOW SWMENU10,HIGH SWMENU10,084,0
SWMENU12	DB	"SWE          OFF",0,LOW SWMENU13,HIGH SWMENU13,LOW SWMENU11,HIGH SWMENU11,004,0
SWMENU13	DB	"SWF           ON",0,LOW SWMENU14,HIGH SWMENU14,LOW SWMENU12,HIGH SWMENU12,085,0
SWMENU14	DB	"SWF          OFF",0,LOW SWMENU15,HIGH SWMENU15,LOW SWMENU13,HIGH SWMENU13,005,0
SWMENU15	DB	"SWG           ON",0,LOW SWMENU16,HIGH SWMENU16,LOW SWMENU14,HIGH SWMENU14,086,0
SWMENU16	DB	"SWG          OFF",0,LOW SWMENU17,HIGH SWMENU17,LOW SWMENU15,HIGH SWMENU15,006,0
SWMENU17	DB	"SWH           ON",0,LOW SWMENU18,HIGH SWMENU18,LOW SWMENU16,HIGH SWMENU16,087,0
SWMENU18	DB	"SWH          OFF",0,LOW SWMENU19,HIGH SWMENU19,LOW SWMENU17,HIGH SWMENU17,007,0
SWMENU19	DB	"SWI        PRESS",0,LOW SWMENU20,HIGH SWMENU20,LOW SWMENU18,HIGH SWMENU18,089,0
SWMENU20	DB	"SWI      RELEASE",0,LOW SWMENU21,HIGH SWMENU21,LOW SWMENU19,HIGH SWMENU19,009,0
SWMENU21	DB	"SWJ            A",0,LOW SWMENU22,HIGH SWMENU22,LOW SWMENU20,HIGH SWMENU20,08B,0
SWMENU22	DB	"SWJ            B",0,LOW SWMENU23,HIGH SWMENU23,LOW SWMENU21,HIGH SWMENU21,04B,0
SWMENU23	DB	"SWJ            C",0,LOW SWMENU24,HIGH SWMENU24,LOW SWMENU22,HIGH SWMENU22,08C,0
SWMENU24	DB	"SWK           ON",0,LOW SWMENU25,HIGH SWMENU25,LOW SWMENU23,HIGH SWMENU23,08D,0
SWMENU25	DB	"SWK          OFF",0,LOW SWMENU26,HIGH SWMENU26,LOW SWMENU24,HIGH SWMENU24,00D,0
SWMENU26	DB	"SWL        PRESS",0,LOW SWMENU27,HIGH SWMENU27,LOW SWMENU25,HIGH SWMENU25,08E,0
SWMENU27	DB	"SWL      RELEASE",0,LOW SWMENU28,HIGH SWMENU28,LOW SWMENU26,HIGH SWMENU26,00E,0
SWMENU28	DB	"SWM        PRESS",0,LOW SWMENU29,HIGH SWMENU29,LOW SWMENU27,HIGH SWMENU27,08F,0
SWMENU29	DB	"SWM      RELEASE",0,LOW SWMENU30,HIGH SWMENU30,LOW SWMENU28,HIGH SWMENU28,00F,0
SWMENU30	DB	"Aileron       ON",0,LOW SWMENU31,HIGH SWMENU31,LOW SWMENU29,HIGH SWMENU29,030,0
SWMENU31	DB	"Aileron      OFF",0,LOW SWMENU32,HIGH SWMENU32,LOW SWMENU30,HIGH SWMENU30,0B0,0
SWMENU32	DB	"Elevator      ON",0,LOW SWMENU33,HIGH SWMENU33,LOW SWMENU31,HIGH SWMENU31,031,0
SWMENU33	DB	"Elevator     OFF",0,LOW SWMENU34,HIGH SWMENU34,LOW SWMENU32,HIGH SWMENU32,0B1,0
SWMENU34	DB	"Rudder        ON",0,LOW SWMENU35,HIGH SWMENU35,LOW SWMENU33,HIGH SWMENU33,032,0
SWMENU35	DB	"Rudder       OFF",0,LOW SWMENU36,HIGH SWMENU36,LOW SWMENU34,HIGH SWMENU34,0B2,0
SWMENU36	DB	"Throttle      ON",0,LOW SWMENU37,HIGH SWMENU37,LOW SWMENU35,HIGH SWMENU35,033,0
SWMENU37	DB	"Throttle     OFF",0,LOW SWMENU1 ,HIGH SWMENU1 ,LOW SWMENU36,HIGH SWMENU36,0B3,0

; The following tables support the options selection calibration menu.

COP1		DB	"   Auto  Trim   ",0,LOW COP2 , HIGH COP2 ,LOW COP13,HIGH COP13,9,080,LOW MATP1, HIGH MATP1
COP2		DB	"Reset Auto Trims",0,LOW COP3 , HIGH COP3 ,LOW COP1 ,HIGH COP1 ,3,08C,LOW YESNO,HIGH YESNO,LOW MRST,HIGH MRST,LOW ATreset,HIGH ATreset
COP3		DB	"   Trim  Zero   ",0,LOW COP4 , HIGH COP4 ,LOW COP2 ,HIGH COP2 ,3,08C,LOW YESNO,HIGH YESNO,LOW MZERO,HIGH MZERO,LOW TrimZero,HIGH TrimZero
COP4		DB	"Clear Trim Zeros",0,LOW COP5 , HIGH COP5 ,LOW COP3 ,HIGH COP3 ,3,08C,LOW YESNO,HIGH YESNO,LOW MCLEAR,HIGH MCLEAR,LOW TrimZeroClear,HIGH TrimZeroClear
COP5		DB	" Alt   Aircraft ",0,LOW COP6 , HIGH COP6 ,LOW COP4 ,HIGH COP4 ,9,080,LOW AMENU1, HIGH AMENU1
COP6		DB	" Copy  Aircraft ",0,LOW COP7 , HIGH COP7 ,LOW COP5 ,HIGH COP5 ,5,08E,LOW Mto, HIGH Mto,LOW MCAN, HIGH MCAN,LOW CopyAFT,HIGH CopyAFT,LOW SetAftRange,HIGH SetAftRange
COP7		DB	"  Set Defaults  ",0,LOW COP11, HIGH COP11,LOW COP6 ,HIGH COP6 ,3,08C,LOW YESNO, HIGH YESNO, LOW MRST, HIGH MRST, LOW SetDefault, HIGH SetDefault
COP8		DB	"Num  prop blades",0,LOW COP9 , HIGH COP9 ,LOW COP7 ,HIGH COP7 ,5,0C8,LOW NumBlades,HIGH NumBlades,LOW MBLADES,HIGH MBLADES,1,0,5,0
COP9		DB	"Retracts Warning",0,LOW COP10, HIGH COP10,LOW COP8 ,HIGH COP8 ,3,088,LOW RetractsWarning, HIGH RetractsWarning,LOW MENA,HIGH MENA
COP10		DB	"   Buddy  Box   ",0,LOW COP11, HIGH COP11,LOW COP7, HIGH COP7 ,9,80, LOW MBB1, HIGH MBB1
COP11		DB	"     Tables     ",0,LOW COP12, HIGH COP12,LOW COP7 ,HIGH COP7 ,9,80, LOW Tables1, HIGH Tables1
COP12		DB	" AUXOUT Control ",0,LOW COP13, HIGH COP13,LOW COP11,HIGH COP11,0,080,LOW MAUXOUT1, HIGH MAUXOUT1,LOW AUXMODE, HIGH AUXMODE
COP13		DB	"EXIT            ",0,LOW COP1 , HIGH COP1 ,LOW COP12,HIGH COP12,3,0  ,LOW EXIT, HIGH EXIT

; Alternate aircraft menu

AMENU1		DB	" Alt #1         ",0,LOW AMENU2 , HIGH AMENU2 ,LOW AMENU13,HIGH AMENU13,5,40,LOW (AltAircraft+1),HIGH AltAircraft,0,0,0,0,D'96',0
AMENU2		DB	" Alt  #1 Switch ",0,LOW AMENU3 , HIGH AMENU3 ,LOW AMENU1 ,HIGH AMENU1 ,6,80,LOW AltAircraft,  HIGH AltAircraft
AMENU3		DB	" Alt #2         ",0,LOW AMENU4 , HIGH AMENU4 ,LOW AMENU2 ,HIGH AMENU2 ,5,40,LOW (AltAircraft+3),HIGH AltAircraft,0,0,0,0,D'96',0
AMENU4		DB	" Alt  #2 Switch ",0,LOW AMENU5 , HIGH AMENU5 ,LOW AMENU3 ,HIGH AMENU3 ,6,80,LOW (AltAircraft+2),HIGH AltAircraft
AMENU5		DB	" Alt #3         ",0,LOW AMENU6 , HIGH AMENU6 ,LOW AMENU4 ,HIGH AMENU4 ,5,40,LOW (AltAircraft+5),HIGH AltAircraft,0,0,0,0,D'96',0
AMENU6		DB	" Alt  #3 Switch ",0,LOW AMENU7 , HIGH AMENU7 ,LOW AMENU5 ,HIGH AMENU5 ,6,80,LOW (AltAircraft+4),HIGH AltAircraft
AMENU7		DB	" Alt #4         ",0,LOW AMENU8 , HIGH AMENU8 ,LOW AMENU6 ,HIGH AMENU6 ,5,40,LOW (AltAircraft+7),HIGH AltAircraft,0,0,0,0,D'96',0
AMENU8		DB	" Alt  #4 Switch ",0,LOW AMENU9 , HIGH AMENU9 ,LOW AMENU7 ,HIGH AMENU7 ,6,80,LOW (AltAircraft+6),HIGH AltAircraft
AMENU9		DB	" Alt #5         ",0,LOW AMENU10, HIGH AMENU10,LOW AMENU8 ,HIGH AMENU8 ,5,40,LOW (AltAircraft+9),HIGH AltAircraft,0,0,0,0,D'96',0
AMENU10		DB	" Alt  #5 Switch ",0,LOW AMENU11, HIGH AMENU11,LOW AMENU9 ,HIGH AMENU9 ,6,80,LOW (AltAircraft+8),HIGH AltAircraft
AMENU11		DB	" Alt #6         ",0,LOW AMENU12, HIGH AMENU12,LOW AMENU10,HIGH AMENU10,5,40,LOW (AltAircraft+D'11'),HIGH AltAircraft,0,0,0,0,D'96',0
AMENU12		DB	" Alt  #6 Switch ",0,LOW AMENU13, HIGH AMENU13,LOW AMENU11,HIGH AMENU11,6,80,LOW (AltAircraft+D'10'),HIGH AltAircraft
AMENU13		DB	"EXIT            ",0,LOW AMENU1 , HIGH AMENU1 ,LOW AMENU12,HIGH AMENU12,3,0 ,LOW EXIT, HIGH EXIT

; Autotrim tables.

MATP1		DB	"AT mode         ",0,LOW MATP2, HIGH MATP2,LOW MATP6, HIGH MATP6,0,0,LOW ATMODE1,HIGH ATMODE1,LOW ATmode,HIGH ATmode
MATP2		DB	"ATthreshold     ",0,LOW MATP3, HIGH MATP3,LOW MATP1, HIGH MATP1,5,0,LOW ATthreshold,HIGH ATthreshold
MATP3		DB	"AT step         ",0,LOW MATP4, HIGH MATP4,LOW MATP2, HIGH MATP2,5,0,LOW AutoTrimStep,HIGH AutoTrimStep
MATP4		DB	"AT ticks        ",0,LOW MATP5, HIGH MATP5,LOW MATP3, HIGH MATP3,5,0,LOW AutoTrimTime,HIGH AutoTrimTime
MATP5		DB	"to TZ           ",0,LOW MATP6, HIGH MATP6,LOW MATP4, HIGH MATP4,3,4,LOW YESNO,HIGH YESNO,0,0,LOW AutoTrim2Zero,High AutoTrim2Zero
MATP6  		DB	"EXIT            ",0,LOW MATP1, HIGH MATP1,LOW MATP5, HIGH MATP5,3,0,LOW EXIT,HIGH EXIT

ATMODE1         DB	"AT mode      Off",0,LOW ATMODE2, HIGH ATMODE2,LOW ATMODE3, HIGH ATMODE3,2,0,LOW ATmode,HIGH ATmode
ATMODE2         DB	"AT mode      Inc",0,LOW ATMODE3, HIGH ATMODE3,LOW ATMODE1, HIGH ATMODE1,0,0,LOW ATmode,HIGH ATmode
ATMODE3         DB	"AT mode One Shot",0,LOW ATMODE1, HIGH ATMODE1,LOW ATMODE2, HIGH ATMODE2,1,0,LOW ATmode,HIGH ATmode

; Table used for selection of the AUXOUT pin function

MAUXOUT1	DB	"       CH1      ",0,LOW MAUXOUT2, HIGH MAUXOUT2,LOW MAUXOUT9, HIGH MAUXOUT9,1,0
MAUXOUT2	DB	"       CH2      ",0,LOW MAUXOUT3, HIGH MAUXOUT3,LOW MAUXOUT1, HIGH MAUXOUT1,3,0
MAUXOUT3	DB	"       CH3      ",0,LOW MAUXOUT4, HIGH MAUXOUT4,LOW MAUXOUT2, HIGH MAUXOUT2,5,0
MAUXOUT4	DB	"       CH4      ",0,LOW MAUXOUT5, HIGH MAUXOUT5,LOW MAUXOUT3, HIGH MAUXOUT3,7,0
MAUXOUT5	DB	"       CH5      ",0,LOW MAUXOUT6, HIGH MAUXOUT6,LOW MAUXOUT4, HIGH MAUXOUT4,9,0
MAUXOUT6	DB	"       CH6      ",0,LOW MAUXOUT7, HIGH MAUXOUT7,LOW MAUXOUT5, HIGH MAUXOUT5,0B,0
MAUXOUT7	DB	"       CH7      ",0,LOW MAUXOUT8, HIGH MAUXOUT8,LOW MAUXOUT6, HIGH MAUXOUT6,0D,0
MAUXOUT8	DB	"       CH8      ",0,LOW MAUXOUT9, HIGH MAUXOUT9,LOW MAUXOUT7, HIGH MAUXOUT7,0F,0
MAUXOUT9	DB	"       PPM      ",0,LOW MAUXOUT1, HIGH MAUXOUT1,LOW MAUXOUT8, HIGH MAUXOUT8,80,0

; Buddy box options

MBB1		DB   	"Master ?        ",0,LOW MBB2, HIGH MBB2,LOW MBB4, HIGH MBB4,3,0,LOW Master, HIGH Master
MBB2		DB   	"  Master  Mode  ",0,LOW MBB3, HIGH MBB3,LOW MBB1, HIGH MBB1,0,0,LOW MMM1, HIGH MMM1, LOW MasterMode, HIGH MasterMode
MBB3		DB   	"Student ?       ",0,LOW MBB4, HIGH MBB4,LOW MBB2, HIGH MBB2,3,0,LOW Student, HIGH Student
MBB4		DB   	"EXIT            ",0,LOW MBB1, HIGH MBB1,LOW MBB3, HIGH MBB3,3,0,LOW EXIT,HIGH EXIT

MMM1		DB   	"M Mode=MicroStar",0,LOW MMM2, HIGH MMM2,LOW MMM2, HIGH MMM2,0,0
MMM2		DB   	"M Mode=Futaba   ",0,LOW MMM1, HIGH MMM1,LOW MMM1, HIGH MMM1,1,0

; Table options

Tables1		DB	"Aircraft Table 1",0,LOW Tables2,HIGH Tables2,LOW Tables11,HIGH Tables11,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Atable1,HIGH Atable1,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables2		DB	"Aircraft Table 2",0,LOW Tables3,HIGH Tables3,LOW Tables1,HIGH Tables1,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Atable2,HIGH Atable2,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables3		DB	"Global  Table  1",0,LOW Tables4,HIGH Tables4,LOW Tables2,HIGH Tables2,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table1,HIGH Table1,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables4		DB	"Global  Table  2",0,LOW Tables5,HIGH Tables5,LOW Tables3,HIGH Tables3,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table2,HIGH Table2,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables5		DB	"Global  Table  3",0,LOW Tables6,HIGH Tables6,LOW Tables4,HIGH Tables4,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table3,HIGH Table3,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables6		DB	"Global  Table  4",0,LOW Tables7,HIGH Tables7,LOW Tables5,HIGH Tables5,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table4,HIGH Table4,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables7		DB	"Global  Table  5",0,LOW Tables8,HIGH Tables8,LOW Tables6,HIGH Tables6,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table5,HIGH Table5,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables8		DB	"Global  Table  6",0,LOW Tables9,HIGH Tables9,LOW Tables7,HIGH Tables7,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table6,HIGH Table6,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables9		DB	"Global  Table  7",0,LOW Tables10,HIGH Tables10,LOW Tables8,HIGH Tables8,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table7,HIGH Table7,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables10	DB	"Global  Table  8",0,LOW Tables11,HIGH Tables11,LOW Tables9,HIGH Tables9,9,86,LOW MTABLE1,HIGH MTABLE1,LOW Table8,HIGH Table8,LOW Temp2Table
		DB	HIGH Temp2Table,LOW Table2Temp,HIGH Table2Temp
Tables11	DB	"EXIT            ",0,LOW Tables1,HIGH Tables1,LOW Tables10,HIGH Tables10,3,0,LOW EXIT,HIGH EXIT

MTABLE1		DB	"POS 0           ",0,LOW MTABLE2 ,HIGH MTABLE2 ,LOW MTABLE12,HIGH MTABLE12,1,0,LOW CalTable, HIGH CalTable
MTABLE2		DB	"POS 1           ",0,LOW MTABLE3 ,HIGH MTABLE3 ,LOW MTABLE1 ,HIGH MTABLE1 ,1,0,LOW (CalTable+1), HIGH CalTable
MTABLE3		DB	"POS 2           ",0,LOW MTABLE4 ,HIGH MTABLE4 ,LOW MTABLE2 ,HIGH MTABLE2 ,1,0,LOW (CalTable+2), HIGH CalTable
MTABLE4		DB	"POS 3           ",0,LOW MTABLE5 ,HIGH MTABLE5 ,LOW MTABLE3 ,HIGH MTABLE3 ,1,0,LOW (CalTable+3), HIGH CalTable
MTABLE5		DB	"POS 4           ",0,LOW MTABLE6 ,HIGH MTABLE6 ,LOW MTABLE4 ,HIGH MTABLE4 ,1,0,LOW (CalTable+4), HIGH CalTable
MTABLE6		DB	"POS 5           ",0,LOW MTABLE7 ,HIGH MTABLE7 ,LOW MTABLE5 ,HIGH MTABLE5 ,1,0,LOW (CalTable+5), HIGH CalTable
MTABLE7		DB	"POS 6           ",0,LOW MTABLE8 ,HIGH MTABLE8 ,LOW MTABLE6 ,HIGH MTABLE6 ,1,0,LOW (CalTable+6), HIGH CalTable
MTABLE8		DB	"POS 7           ",0,LOW MTABLE9 ,HIGH MTABLE9 ,LOW MTABLE7 ,HIGH MTABLE7 ,1,0,LOW (CalTable+7), HIGH CalTable
MTABLE9		DB	"POS 8           ",0,LOW MTABLE10,HIGH MTABLE10,LOW MTABLE8 ,HIGH MTABLE8 ,1,0,LOW (CalTable+8), HIGH CalTable
MTABLE10	DB	"POS 9           ",0,LOW MTABLE11,HIGH MTABLE11,LOW MTABLE9 ,HIGH MTABLE9 ,1,0,LOW (CalTable+9), HIGH CalTable
MTABLE11	DB	"POS 10          ",0,LOW MTABLE12,HIGH MTABLE12,LOW MTABLE10,HIGH MTABLE10,1,0,LOW (CalTable+0a), HIGH CalTable
MTABLE12	DB	"EXIT            ",0,LOW MTABLE1 ,HIGH MTABLE1 ,LOW MTABLE11,HIGH MTABLE11,3,0,LOW EXIT,HIGH EXIT

; The following tables support the system setup calibration menu.

SYS1		DB	" TX Volt  Meter ",0,LOW SYS2, HIGH SYS2, LOW SYS22,HIGH SYS22,7,88 ,LOW TXvoltSet, HIGH TXvoltSet, LOW MVOLTS, HIGH MVOLTS
SYS2		DB	"TX Alarm Voltage",0,LOW SYS3, HIGH SYS3, LOW SYS1 ,HIGH SYS1 ,8,0C8,LOW BattAlarm, HIGH BattAlarm, LOW MVOLTS, HIGH MVOLTS, 0,0,0FF,00
SYS3		DB	"Reset Batt Timer",0,LOW SYS5, HIGH SYS5, LOW SYS2 ,HIGH SYS2 ,3,8C ,LOW YESNO, HIGH YESNO, LOW MRST, HIGH MRST,LOW ResetBatTimer,HIGH ResetBatTimer 
SYS4		DB	" RX Volt  Meter ",0,LOW SYS5, HIGH SYS5, LOW SYS3 ,HIGH SYS3 ,7,88 ,LOW RXvoltSet, HIGH RXvoltSet, LOW MVOLTS, HIGH MVOLTS
SYS5		DB	"Servo  Min Pulse",0,LOW SYS6, HIGH SYS6, LOW SYS3 ,HIGH SYS3 ,2,0C8,LOW ServoMin,HIGH ServoMin,LOW MSYNC,HIGH MSYNC,LOW D'1000',HIGH D'1000',LOW D'5000',HIGH D'5000'
SYS6		DB	"Servo  Max Pulse",0,LOW SYS7, HIGH SYS7, LOW SYS5 ,HIGH SYS5 ,2,0C8,LOW ServoMax,HIGH ServoMax,LOW MSYNC, HIGH MSYNC,LOW D'1000',HIGH D'1000',LOW D'5000',HIGH D'5000'
SYS7		DB	"Number  Channels",0,LOW SYS8, HIGH SYS8, LOW SYS6 ,HIGH SYS6 ,5,0CE,LOW MaxChannels,HIGH MaxChannels,LOW MNUMCH,HIGH MNUMCH,4,0,9,0, LOW PostChan
		DB			   HIGH PostChan, LOW PreChan, HIGH PreChan
SYS8		DB	"   Sync width   ",0,LOW SYS9, HIGH SYS9, LOW SYS7 ,HIGH SYS7 ,2,0C8,LOW SyncWidth, HIGH SyncWidth,LOW MSYNC,HIGH MSYNC,LOW D'200',HIGH D'200',LOW D'1500',HIGH D'1500'
SYS9		DB	"  Shift Invert  ",0,LOW SYS10,HIGH SYS10,LOW SYS8 ,HIGH SYS8 ,3,88 ,LOW SHIFT, HIGH SHIFT,LOW MSHFINV, HIGH MSHFINV
SYS10		DB	"  Format Flash  ",0,LOW SYS11,HIGH SYS11,LOW SYS9 ,HIGH SYS9 ,7,80 ,LOW FmtFlsh, HIGH FmtFlsh
SYS11		DB	"    Configure   ",0,LOW SYS12,HIGH SYS12,LOW SYS10,HIGH SYS10,9,80 ,LOW SCALCFG1, HIGH SCALCFG1
SYS12		DB	"  JoyStick Cal  ",0,LOW SYS13,HIGH SYS13,LOW SYS11,HIGH SYS11,9,80 ,LOW JSCAL1, HIGH JSCAL1
SYS13		DB	"       FMS      ",0,LOW SYS16,HIGH SYS16,LOW SYS12,HIGH SYS12,3,8C ,LOW FMSflagU1, HIGH FMSflagU1, LOW MENA, HIGH MENA,LOW FMSenable,HIGH FMSenable
SYS14		DB	"   FMS UART 2   ",0,LOW SYS15,HIGH SYS15,LOW SYS13,HIGH SYS13,3,8C ,LOW FMSflag, HIGH FMSflag, LOW MENA, HIGH MENA,LOW FMSenable,HIGH FMSenable
SYS15		DB	" Frequency Band ",0,LOW SYS16,HIGH SYS16,LOW SYS14,HIGH SYS14,0,84 ,LOW SFBAND1, HIGH SFBAND1, LOW Fband, HIGH Fband, LOW PostBand, HIGH PostBand
SYS16		DB	" Buzzer  Invert ",0,LOW SYS17,HIGH SYS17,LOW SYS13,HIGH SYS13,3,88 ,LOW BuzPol,HIGH BuzPol,LOW MINVERT,HIGH MINVERT
SYS17		DB	"A,E,R,TrmCtrBeep",0,LOW SYS18,HIGH SYS18,LOW SYS16,HIGH SYS16,3,88 ,LOW TrimCenterBeepFlag,HIGH TrimCenterBeepFlag,LOW MENA,HIGH MENA
SYS18		DB	" Tht TrmCtrBeep ",0,LOW SYS19,HIGH SYS19,LOW SYS17,HIGH SYS17,3,88 ,LOW ThtTCenterBeepFlag,HIGH ThtTCenterBeepFlag,LOW MENA,HIGH MENA
SYS19		DB	"CH6&7 TrmCtrBeep",0,LOW SYS20,HIGH SYS20,LOW SYS18,HIGH SYS18,3,88 ,LOW CH67CenterBeepFlag,HIGH CH67CenterBeepFlag,LOW MENA,HIGH MENA
SYS20		DB	"DTrimAdjustDelay",0,LOW SYS21,HIGH SYS21,LOW SYS19,HIGH SYS19,5,0C8,LOW DTrimAdjustDelay,HIGH DTrimAdjustDelay,LOW MDELAY,HIGH MDELAY,D'3',0,D'20',00
SYS21		DB	"  Display  Mode ",0,LOW SYS22,HIGH SYS22,LOW SYS20,HIGH SYS20,0,80 ,LOW SDMODE1, HIGH SDMODE1, LOW DisplayMode, HIGH DisplayMode
SYS22		DB	"EXIT            ",0,LOW SYS1 ,HIGH SYS1, LOW SYS21,HIGH SYS21,3,0 , LOW EXIT,HIGH EXIT

SDMODE1		DB	"   Alternate    ",0,LOW SDMODE2, HIGH SDMODE2,LOW SDMODE2, HIGH SDMODE2,0  ,0
SDMODE2		DB	"Auto Trim Select",0,LOW SDMODE1, HIGH SDMODE1,LOW SDMODE1, HIGH SDMODE1,0FF,0

SFBAND1		DB	"     No  RF     ",0,LOW SFBAND2, HIGH SFBAND2,LOW SFBAND4, HIGH SFBAND4,0,0
SFBAND2		DB	"     50  MHz    ",0,LOW SFBAND3, HIGH SFBAND3,LOW SFBAND1, HIGH SFBAND1,1,0
SFBAND3		DB	"     53  MHz    ",0,LOW SFBAND4, HIGH SFBAND4,LOW SFBAND2, HIGH SFBAND2,2,0
SFBAND4		DB	"     72  MHz    ",0,LOW SFBAND1, HIGH SFBAND1,LOW SFBAND3, HIGH SFBAND3,3,0

; Transmitter configuration menus, these menus allow the pilot to define the transmitter output
; channel order and the trim assignment.

SCALCFG1	DB	" Channel  Order ",0,LOW SCALCFG2 ,HIGH SCALCFG2 ,LOW SCALCFG14,HIGH SCALCFG14,0,84,LOW SCHORD1, HIGH SCHORD1, LOW Atemp, HIGH Atemp, LOW PostSetOrder, HIGH PostSetOrder
SCALCFG2	DB	"Output channel 1",0,LOW SCALCFG3 ,HIGH SCALCFG3 ,LOW SCALCFG1 ,HIGH SCALCFG1 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW ChannelOrder, HIGH ChannelOrder
SCALCFG3	DB	"Output channel 2",0,LOW SCALCFG4 ,HIGH SCALCFG4 ,LOW SCALCFG2 ,HIGH SCALCFG2 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+1), HIGH ChannelOrder
SCALCFG4	DB	"Output channel 3",0,LOW SCALCFG5 ,HIGH SCALCFG5 ,LOW SCALCFG3 ,HIGH SCALCFG3 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+2), HIGH ChannelOrder
SCALCFG5	DB	"Output channel 4",0,LOW SCALCFG6 ,HIGH SCALCFG6 ,LOW SCALCFG4 ,HIGH SCALCFG4 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+3), HIGH ChannelOrder
SCALCFG6	DB	"Output channel 5",0,LOW SCALCFG7 ,HIGH SCALCFG7 ,LOW SCALCFG5 ,HIGH SCALCFG5 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+4), HIGH ChannelOrder
SCALCFG7	DB	"Output channel 6",0,LOW SCALCFG8 ,HIGH SCALCFG8 ,LOW SCALCFG6 ,HIGH SCALCFG6 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+5), HIGH ChannelOrder
SCALCFG8	DB	"Output channel 7",0,LOW SCALCFG9 ,HIGH SCALCFG9 ,LOW SCALCFG7 ,HIGH SCALCFG7 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+6), HIGH ChannelOrder
SCALCFG9	DB	"Output channel 8",0,LOW SCALCFG10,HIGH SCALCFG10,LOW SCALCFG8 ,HIGH SCALCFG8 ,0,80,LOW SCALCH1, HIGH SCALCH1, LOW (ChannelOrder+7), HIGH ChannelOrder
SCALCFG10	DB	"Select Ail  Trim",0,LOW SCALCFG11,HIGH SCALCFG11,LOW SCALCFG9 ,HIGH SCALCFG9 ,0,80,LOW SCALTRIM1, HIGH SCALTRIM1, LOW AilTrimCh, HIGH AilTrimCh
SCALCFG11	DB	"Select Ele  Trim",0,LOW SCALCFG12,HIGH SCALCFG12,LOW SCALCFG10,HIGH SCALCFG10,0,80,LOW SCALTRIM1, HIGH SCALTRIM1, LOW EleTrimCh, HIGH EleTrimCh
SCALCFG12	DB	"Select Rud  Trim",0,LOW SCALCFG13,HIGH SCALCFG13,LOW SCALCFG11,HIGH SCALCFG11,0,80,LOW SCALTRIM1, HIGH SCALTRIM1, LOW RudTrimCh, HIGH RudTrimCh
SCALCFG13	DB	"Select Tht  Trim",0,LOW SCALCFG14,HIGH SCALCFG14,LOW SCALCFG12,HIGH SCALCFG12,0,80,LOW SCALTRIM1, HIGH SCALTRIM1, LOW ThtTrimCh, HIGH ThtTrimCh
SCALCFG14	DB	"EXIT            ",0,LOW SCALCFG1 ,HIGH SCALCFG1 ,LOW SCALCFG13,HIGH SCALCFG13,3,0,LOW EXIT, HIGH EXIT

SCHORD1		DB	"       ACE      ",0,LOW SCHORD2, HIGH SCHORD2,LOW SCHORD4, HIGH SCHORD4,1,0
SCHORD2		DB	"     Futaba     ",0,LOW SCHORD3, HIGH SCHORD3,LOW SCHORD1, HIGH SCHORD1,2,0
SCHORD3		DB	"   Airtronics   ",0,LOW SCHORD4, HIGH SCHORD4,LOW SCHORD2, HIGH SCHORD2,3,0
SCHORD4		DB	"       JR       ",0,LOW SCHORD1, HIGH SCHORD1,LOW SCHORD3, HIGH SCHORD3,4,0

SCALCH1		DB	"    Aileron     ",0,LOW SCALCH2, HIGH SCALCH2,LOW SCALCH8, HIGH SCALCH8,1,0,LOW STRIM, HIGH STRIM
SCALCH2		DB	"    Elevator    ",0,LOW SCALCH3, HIGH SCALCH3,LOW SCALCH1, HIGH SCALCH1,2,0,LOW STRIM, HIGH STRIM
SCALCH3		DB	"     Rudder     ",0,LOW SCALCH4, HIGH SCALCH4,LOW SCALCH2, HIGH SCALCH2,3,0,LOW STRIM, HIGH STRIM
SCALCH4		DB	"    Throttle    ",0,LOW SCALCH5, HIGH SCALCH5,LOW SCALCH3, HIGH SCALCH3,4,0,LOW STRIM, HIGH STRIM
SCALCH5		DB	"       CH5      ",0,LOW SCALCH6, HIGH SCALCH6,LOW SCALCH4, HIGH SCALCH4,5,0,LOW STRIM, HIGH STRIM
SCALCH6		DB	"       CH6      ",0,LOW SCALCH7, HIGH SCALCH7,LOW SCALCH5, HIGH SCALCH5,6,0,LOW STRIM, HIGH STRIM
SCALCH7		DB	"       CH7      ",0,LOW SCALCH8, HIGH SCALCH8,LOW SCALCH6, HIGH SCALCH6,7,0,LOW STRIM, HIGH STRIM
SCALCH8		DB	"       CH8      ",0,LOW SCALCH1, HIGH SCALCH1,LOW SCALCH7, HIGH SCALCH7,8,0,LOW STRIM, HIGH STRIM

SCALTRIM1	DB	"    No  Trim    ",0,LOW SCALTRIM2, HIGH SCALTRIM2, LOW SCALTRIM9, HIGH SCALTRIM9, 0,0,LOW STRIM, HIGH STRIM
SCALTRIM2	DB	"     Trim 1     ",0,LOW SCALTRIM3, HIGH SCALTRIM3, LOW SCALTRIM1, HIGH SCALTRIM1, 1,0,LOW STRIM, HIGH STRIM
SCALTRIM3	DB	"     Trim 2     ",0,LOW SCALTRIM4, HIGH SCALTRIM4, LOW SCALTRIM2, HIGH SCALTRIM2, 2,0,LOW STRIM, HIGH STRIM
SCALTRIM4	DB	"     Trim 3     ",0,LOW SCALTRIM5, HIGH SCALTRIM5, LOW SCALTRIM3, HIGH SCALTRIM3, 3,0,LOW STRIM, HIGH STRIM
SCALTRIM5	DB	"     Trim 4     ",0,LOW SCALTRIM6, HIGH SCALTRIM6, LOW SCALTRIM4, HIGH SCALTRIM4, 4,0,LOW STRIM, HIGH STRIM
SCALTRIM6	DB	" Digital Trim 1 ",0,LOW SCALTRIM7, HIGH SCALTRIM7, LOW SCALTRIM5, HIGH SCALTRIM5,10,0,LOW STRIM, HIGH STRIM
SCALTRIM7	DB	" Digital Trim 2 ",0,LOW SCALTRIM8, HIGH SCALTRIM8, LOW SCALTRIM6, HIGH SCALTRIM6,20,0,LOW STRIM, HIGH STRIM
SCALTRIM8	DB	" Digital Trim 3 ",0,LOW SCALTRIM9, HIGH SCALTRIM9, LOW SCALTRIM7, HIGH SCALTRIM7,30,0,LOW STRIM, HIGH STRIM
SCALTRIM9	DB	" Digital Trim 4 ",0,LOW SCALTRIM1, HIGH SCALTRIM1, LOW SCALTRIM8, HIGH SCALTRIM8,40,0,LOW STRIM, HIGH STRIM

; Joy stick calibration...

JSCAL1		DB	"    Aileron     ",0,LOW JSCAL2, HIGH JSCAL2, LOW JSCAL11,HIGH JSCAL11,7,80,LOW JScChan,HIGH JScChan,LOW AHG,4
JSCAL2		DB	"    Elevator    ",0,LOW JSCAL3, HIGH JSCAL3, LOW JSCAL1, HIGH JSCAL1, 7,80,LOW JScChan,HIGH JScChan,LOW EHG,5
JSCAL3		DB	"    Rudder      ",0,LOW JSCAL4, HIGH JSCAL4, LOW JSCAL2, HIGH JSCAL2, 7,80,LOW JScChan,HIGH JScChan,LOW RHG,6
JSCAL4		DB	"    Throttle    ",0,LOW JSCAL5, HIGH JSCAL5, LOW JSCAL3, HIGH JSCAL3, 7,80,LOW JSncChan,HIGH JSncChan,LOW THG,7
JSCAL5		DB	"      CH6       ",0,LOW JSCAL6, HIGH JSCAL6, LOW JSCAL4, HIGH JSCAL4, 7,80,LOW JStrimsChan,HIGH JStrimsChan,LOW CH6HG,0
JSCAL6		DB	"      CH7       ",0,LOW JSCAL7, HIGH JSCAL7, LOW JSCAL5, HIGH JSCAL5, 7,80,LOW JStrimsChan,HIGH JStrimsChan,LOW CH7HG,1
JSCAL7		DB	"  Aileron trim  ",0,LOW JSCAL8, HIGH JSCAL8, LOW JSCAL6, HIGH JSCAL6, 7,80,LOW JStrimsChan,HIGH JStrimsChan,LOW AtrimHG,8
JSCAL8		DB	" Elevator  trim ",0,LOW JSCAL9, HIGH JSCAL9, LOW JSCAL7, HIGH JSCAL7, 7,80,LOW JStrimsChan,HIGH JStrimsChan,LOW EtrimHG,9
JSCAL9		DB	"  Rudder  trim  ",0,LOW JSCAL10,HIGH JSCAL10,LOW JSCAL8, HIGH JSCAL8, 7,80,LOW JStrimsChan,HIGH JStrimsChan,LOW RtrimHG,0A
JSCAL10		DB	" Throttle  trim ",0,LOW JSCAL11,HIGH JSCAL11,LOW JSCAL9, HIGH JSCAL9, 7,80,LOW JStrimsChan,HIGH JStrimsChan,LOW TtrimHG,0B
JSCAL11		DB	"Exit            ",0,LOW JSCAL1 ,HIGH JSCAL1 ,LOW JSCAL10,HIGH JSCAL10,3,0,LOW EXIT, HIGH EXIT

JCALMES14	DB	"    Center      ",0
JCALMES15	DB	"   Right/Down   ",0
JCALMES16	DB      "    Left/Up     ",0

; The following table support preliminary control remapping using translation tables. This function
; is performed before any trims are applied and it is not switch selectable. This is designed
; to perform a preliminary remaping of a control channel before any other action is taken.
PRMAP1		DB	"  Aileron Remap ",0,LOW PRMAP2,HIGH PRMAP2,LOW PRMAP7,HIGH PRMAP7,0, 80,LOW MTBL1,HIGH MTBL1,LOW AILremap,HIGH AILremap
PRMAP2		DB	" Elevator Remap ",0,LOW PRMAP3,HIGH PRMAP3,LOW PRMAP1,HIGH PRMAP1,0, 80,LOW MTBL1,HIGH MTBL1,LOW ELEremap,HIGH ELEremap
PRMAP3		DB	"  Rudder  Remap ",0,LOW PRMAP4,HIGH PRMAP4,LOW PRMAP2,HIGH PRMAP2,0, 80,LOW MTBL1,HIGH MTBL1,LOW RUDremap,HIGH RUDremap
PRMAP4		DB	" Throttle Remap ",0,LOW PRMAP5,HIGH PRMAP5,LOW PRMAP3,HIGH PRMAP3,0, 80,LOW MTBL1,HIGH MTBL1,LOW THTremap,HIGH THTremap
PRMAP5		DB	"    CH6 Remap   ",0,LOW PRMAP6,HIGH PRMAP6,LOW PRMAP4,HIGH PRMAP4,0, 80,LOW MTBL1,HIGH MTBL1,LOW CH6remap,HIGH CH6remap
PRMAP6		DB	"    CH7 Remap   ",0,LOW PRMAP7,HIGH PRMAP7,LOW PRMAP5,HIGH PRMAP5,0, 80,LOW MTBL1,HIGH MTBL1,LOW CH7remap,HIGH CH7remap
PRMAP7		DB	"EXIT            ",0,LOW PRMAP1,HIGH PRMAP1,LOW PRMAP6,HIGH PRMAP6,3 , 0,LOW EXIT,HIGH EXIT

; The following tables support the advance setup calibration menu.

ADV1		DB	" Framing   Rate ",0,LOW ADV2, HIGH ADV2, LOW ADV7 ,HIGH ADV7 ,05,0C8,LOW TicksPer, HIGH TicksPer, LOW MHZ, HIGH MHZ,D'32',0,D'50',00
ADV2		DB	" FrameRateDefect",0,LOW ADV5, HIGH ADV5, LOW ADV1 ,HIGH ADV1 ,0B,088,LOW FrameDefect, HIGH FrameDefect, LOW MDEFECT, HIGH MDEFECT
ADV3		DB	" PLL  Ref  Freq ",0,LOW ADV4, HIGH ADV4, LOW ADV2 ,HIGH ADV2 ,0C,8E ,LOW Rreg50, HIGH Rreg50, LOW MKHZ, HIGH MKHZ,LOW PostRef,HIGH PostRef,LOW PreRef,HIGH PreRef 
ADV4		DB	"  Send  Serial  ",0,LOW ADV5, HIGH ADV5, LOW ADV3 ,HIGH ADV3 ,3 ,8C ,LOW SerialSend, HIGH SerialSend,LOW MENA,HIGH MENA, LOW USART2init, HIGH USART2init
ADV5		DB	" Control  Remap ",0,LOW ADV6, HIGH ADV6, LOW ADV2 ,HIGH ADV2 ,9, 80 ,LOW PRMAP1, HIGH PRMAP1
ADV6		DB	"ADC glitch Thres",0,LOW ADV7, HIGH ADV7, LOW ADV5 ,HIGH ADV5 ,5, 88 ,LOW ADCfixThres, HIGH ADCfixThres, LOW MLEVEL, HIGH MLEVEL
ADV7		DB	"EXIT            ",0,LOW ADV1 ,HIGH ADV1, LOW ADV6 ,HIGH ADV6 ,3 ,0  ,LOW EXIT,HIGH EXIT

; The following tables support helicopter calibration and setup menus

HELI1		DB	"Helicopter  Mode",0,LOW HELI2, HIGH HELI2, LOW HELI9 ,HIGH HELI9 ,3, 88,LOW Henable, HIGH Henable,LOW MENA,HIGH MENA
HELI2		DB	" Gyro Sens Tune ",0,LOW HELI3, HIGH HELI3, LOW HELI1 ,HIGH HELI1 ,3, 88,LOW GyroTune, HIGH GyroTune,LOW MENA,HIGH MENA
HELI3		DB	"      CCPM      ",0,LOW HELI4, HIGH HELI4, LOW HELI2 ,HIGH HELI2 ,0, 80,LOW MCCPM1, HIGH MCCPM1,LOW CCPMmode, HIGH CCPMmode
HELI4		DB	" Pitch  Reverse ",0,LOW HELI5, HIGH HELI5, LOW HELI3 ,HIGH HELI3 ,3, 88,LOW HPrev, HIGH HPrev,LOW MENA,HIGH MENA
HELI5		DB	"  Normal  Mode  ",0,LOW HELI6, HIGH HELI6, LOW HELI4 ,HIGH HELI4 ,9, 80,LOW MNORM1, HIGH MNORM1
HELI6		DB	"ThrottleHoldMode",0,LOW HELI7, HIGH HELI7, LOW HELI5 ,HIGH HELI5 ,9, 80,LOW MTHOLD1, HIGH MTHOLD1
HELI7		DB	"  Stunt mode 1  ",0,LOW HELI8, HIGH HELI8, LOW HELI6 ,HIGH HELI6 ,9, 80,LOW MSTUNT11, HIGH MSTUNT11
HELI8		DB	"  Stunt mode 2  ",0,LOW HELI9, HIGH HELI9, LOW HELI7 ,HIGH HELI7 ,9, 80,LOW MSTUNT21, HIGH MSTUNT21
HELI9		DB	"EXIT            ",0,LOW HELI1, HIGH HELI1, LOW HELI8 ,HIGH HELI8 ,3,  0,LOW EXIT, HIGH EXIT

MCCPM1 		DB	"       Off      ",0,LOW MCCPM2, HIGH MCCPM2, LOW MCCPM4, HIGH MCCPM4,0,0
MCCPM2 		DB	"   3 servo 120  ",0,LOW MCCPM3, HIGH MCCPM3, LOW MCCPM1, HIGH MCCPM1,1,0
MCCPM3	 	DB	"   3 servo 140  ",0,LOW MCCPM4, HIGH MCCPM4, LOW MCCPM2, HIGH MCCPM2,2,0
MCCPM4	 	DB	"   3 servo  90  ",0,LOW MCCPM1, HIGH MCCPM1, LOW MCCPM3, HIGH MCCPM3,3,0

MNORM1		DB	"IdleUp  Norm  SW",0,LOW MNORM2, HIGH MNORM2, LOW MNORM6 ,HIGH MNORM6 ,6, 80,LOW SWIDLEUPN, HIGH SWIDLEUPN
MNORM2		DB	"IdleUp  Norm Pos",0,LOW MNORM3, HIGH MNORM3, LOW MNORM1 ,HIGH MNORM1 ,1,0C8,LOW IdleUpNorm, HIGH IdleUpNorm, LOW MPOS, HIGH MPOS,0,0,D'100',0
MNORM3		DB	" Throttle Table ",0,LOW MNORM4, HIGH MNORM4, LOW MNORM2 ,HIGH MNORM2 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW HTht,HIGH HTht
MNORM4		DB	"  Pitch  Table  ",0,LOW MNORM5, HIGH MNORM5, LOW MNORM3 ,HIGH MNORM3 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW HPitch,HIGH HPitch
MNORM5		DB	"Gyro Sensitivity",0,LOW MNORM6, HIGH MNORM6, LOW MNORM4 ,HIGH MNORM4 ,1,0C8,LOW HSen, HIGH HSen, LOW MPOS, HIGH MPOS,0,0,D'100',0
MNORM6		DB	"EXIT            ",0,LOW MNORM1, HIGH MNORM1, LOW MNORM5 ,HIGH MNORM5 ,3,  0,LOW EXIT, HIGH EXIT

MTHOLD1		DB	"Throttle hold SW",0,LOW MTHOLD2, HIGH MTHOLD2, LOW MTHOLD6 ,HIGH MTHOLD6 ,6, 80,LOW SWTHOLD, HIGH SWTHOLD
MTHOLD2		DB	" Hold  Position ",0,LOW MTHOLD3, HIGH MTHOLD3, LOW MTHOLD1 ,HIGH MTHOLD1 ,1,0C8,LOW THOLDp, HIGH THOLDp, LOW MPOS, HIGH MPOS,0,0,D'100',0
MTHOLD3		DB	"Transistion Time",0,LOW MTHOLD4, HIGH MTHOLD4, LOW MTHOLD2 ,HIGH MTHOLD2 ,8, 8E,LOW TtransistionT,HIGH TtransistionT,LOW MTSEC,HIGH MTSEC,LOW PostTTT
		DB			     HIGH PostTTT, LOW PreTTT, HIGH PreTTT
MTHOLD4		DB	"  Pitch  Table  ",0,LOW MTHOLD5, HIGH MTHOLD5, LOW MTHOLD3 ,HIGH MTHOLD3 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW HthtPitch,HIGH HthtPitch
MTHOLD5		DB	"Gyro Sensitivity",0,LOW MTHOLD6, HIGH MTHOLD6, LOW MTHOLD4 ,HIGH MTHOLD4 ,1,0C8,LOW HthtSen, HIGH HthtSen, LOW MPOS, HIGH MPOS,0,0,D'100',0
MTHOLD6		DB	"EXIT            ",0,LOW MTHOLD1, HIGH MTHOLD1, LOW MTHOLD5 ,HIGH MTHOLD5 ,3,  0,LOW EXIT, HIGH EXIT

MSTUNT11	DB	"Stunt  mode 1 SW",0,LOW MSTUNT12, HIGH MSTUNT12, LOW MSTUNT17 ,HIGH MSTUNT17 ,6, 80,LOW SWSTUNT1, HIGH SWSTUNT1
MSTUNT12	DB	"IdleUp  ST 1  SW",0,LOW MSTUNT13, HIGH MSTUNT13, LOW MSTUNT11 ,HIGH MSTUNT11 ,6, 80,LOW SWIDLEUPST1, HIGH SWIDLEUPST1
MSTUNT13	DB	"IdleUp  ST 1 Pos",0,LOW MSTUNT14, HIGH MSTUNT14, LOW MSTUNT12 ,HIGH MSTUNT12 ,1,0C8,LOW IdleUpST1, HIGH IdleUpST1, LOW MPOS, HIGH MPOS,0,0,D'100',0
MSTUNT14	DB	" Throttle Table ",0,LOW MSTUNT15, HIGH MSTUNT15, LOW MSTUNT13 ,HIGH MSTUNT13 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW Hst1Tht,HIGH Hst1Tht
MSTUNT15	DB	"  Pitch  Table  ",0,LOW MSTUNT16, HIGH MSTUNT16, LOW MSTUNT14 ,HIGH MSTUNT14 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW Hst1Pitch,HIGH Hst1Pitch
MSTUNT16	DB	"Gyro Sensitivity",0,LOW MSTUNT17, HIGH MSTUNT17, LOW MSTUNT15 ,HIGH MSTUNT15 ,1,0C8,LOW Hst1Sen, HIGH Hst1Sen, LOW MPOS, HIGH MPOS,0,0,D'100',0
MSTUNT17	DB	"EXIT            ",0,LOW MSTUNT11, HIGH MSTUNT11, LOW MSTUNT16 ,HIGH MSTUNT16 ,3,  0,LOW EXIT, HIGH EXIT

MSTUNT21	DB	"Stunt  mode 2 SW",0,LOW MSTUNT22, HIGH MSTUNT22, LOW MSTUNT27 ,HIGH MSTUNT27 ,6, 80,LOW SWSTUNT2, HIGH SWSTUNT2
MSTUNT22	DB	"IdleUp  ST 2  SW",0,LOW MSTUNT23, HIGH MSTUNT23, LOW MSTUNT21 ,HIGH MSTUNT21 ,6, 80,LOW SWIDLEUPST2, HIGH SWIDLEUPST2
MSTUNT23	DB	"IdleUp  ST 2 Pos",0,LOW MSTUNT24, HIGH MSTUNT24, LOW MSTUNT22 ,HIGH MSTUNT22 ,1,0C8,LOW IdleUpST2, HIGH IdleUpST2, LOW MPOS, HIGH MPOS,0,0,D'100',0
MSTUNT24	DB	" Throttle Table ",0,LOW MSTUNT25, HIGH MSTUNT25, LOW MSTUNT23 ,HIGH MSTUNT23 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW Hst2Tht,HIGH Hst2Tht
MSTUNT25	DB	"  Pitch  Table  ",0,LOW MSTUNT26, HIGH MSTUNT26, LOW MSTUNT24 ,HIGH MSTUNT24 ,0, 80,LOW MTBL1,HIGH MTBL1,LOW Hst2Pitch,HIGH Hst2Pitch
MSTUNT26	DB	"Gyro Sensitivity",0,LOW MSTUNT27, HIGH MSTUNT27, LOW MSTUNT25 ,HIGH MSTUNT25 ,1,0C8,LOW Hst2Sen, HIGH Hst2Sen, LOW MPOS, HIGH MPOS,0,0,D'100',0
MSTUNT27	DB	"EXIT            ",0,LOW MSTUNT21, HIGH MSTUNT21, LOW MSTUNT26 ,HIGH MSTUNT26 ,3,  0,LOW EXIT, HIGH EXIT


